# Generated by Django 4.1.4 on 2022-12-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Звёзды'),
        ),
    ]
